namespace AvionicsInstrumentControlDemo
{
    partial class DemoWindow
    {
        /// <summary>
        /// Variables necessary to the designer
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Cleaning the resources used
        /// </summary>
        /// <param name="disposing">true if managed resources should be removed; otherwise, false</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Windows Form Designer

        /// <summary>
        ///Required method for the management of the designer - do not change
        /// The contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(DemoWindow));
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.avgTemperatureLabel = new System.Windows.Forms.Label();
            this.avgPressureLabel = new System.Windows.Forms.Label();
            this.avgVerticalSpeedLabel = new System.Windows.Forms.Label();
            this.avgAltitudeLabel = new System.Windows.Forms.Label();
            this.label17 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.relAltitudelabel = new System.Windows.Forms.Label();
            this.serialTemperaturelabel = new System.Windows.Forms.Label();
            this.serialPressurelabel = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.serialHeadinglabel = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.serialVerticalLabel = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.serialAltitudeLabel = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.serialPort1 = new System.IO.Ports.SerialPort(this.components);
            this.startButton = new System.Windows.Forms.Button();
            this.stopButton = new System.Windows.Forms.Button();
            this.comboBox1 = new System.Windows.Forms.ComboBox();
            this.resetRelButton = new System.Windows.Forms.Button();
            this.telemetryGroupBox = new System.Windows.Forms.GroupBox();
            this.altiLabel = new System.Windows.Forms.Label();
            this.tempLabel = new System.Windows.Forms.Label();
            this.pressureLabel = new System.Windows.Forms.Label();
            this.magLabelZ = new System.Windows.Forms.Label();
            this.magLabelY = new System.Windows.Forms.Label();
            this.magLabelX = new System.Windows.Forms.Label();
            this.gyroLabelZ = new System.Windows.Forms.Label();
            this.gyroLabelY = new System.Windows.Forms.Label();
            this.gyroLabelX = new System.Windows.Forms.Label();
            this.accelLabelZ = new System.Windows.Forms.Label();
            this.accelLabelY = new System.Windows.Forms.Label();
            this.accelLabelX = new System.Windows.Forms.Label();
            this.label16 = new System.Windows.Forms.Label();
            this.label15 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.telemetryCheckBox1 = new System.Windows.Forms.CheckBox();
            this.clearMarkersButton = new System.Windows.Forms.Button();
            this.gMapControl1 = new GMap.NET.WindowsForms.GMapControl();
            this.addMarkerButton = new System.Windows.Forms.Button();
            this.zoomLabel = new System.Windows.Forms.Label();
            this.timeLabel = new System.Windows.Forms.Label();
            this.showGraphButton = new System.Windows.Forms.Button();
            this.statusLabel = new System.Windows.Forms.Label();
            this.fileLabel = new System.Windows.Forms.Label();
            this.randomGenButton = new System.Windows.Forms.Button();
            this.gpsStatusLabel = new System.Windows.Forms.Label();
            this.leftCameraButton = new System.Windows.Forms.Button();
            this.centerCameraButton = new System.Windows.Forms.Button();
            this.rightCameraButton = new System.Windows.Forms.Button();
            this.cameraLabel = new System.Windows.Forms.Label();
            this.tempIndicator1 = new AvionicsInstrumentControlDemo.TempIndicator();
            this.horizonInstrumentControl1 = new AvionicsInstrumentControlDemo.AttitudeIndicatorInstrumentControl();
            this.verticalSpeedInstrumentControl1 = new AvionicsInstrumentControlDemo.VerticalSpeedIndicatorInstrumentControl();
            this.headingIndicatorInstrumentControl1 = new AvionicsInstrumentControlDemo.HeadingIndicatorInstrumentControl();
            this.altimeterInstrumentControl1 = new AvionicsInstrumentControlDemo.AltimeterInstrumentControl();
            this.groupBox1.SuspendLayout();
            this.telemetryGroupBox.SuspendLayout();
            this.SuspendLayout();
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.avgTemperatureLabel);
            this.groupBox1.Controls.Add(this.avgPressureLabel);
            this.groupBox1.Controls.Add(this.avgVerticalSpeedLabel);
            this.groupBox1.Controls.Add(this.avgAltitudeLabel);
            this.groupBox1.Controls.Add(this.label17);
            this.groupBox1.Controls.Add(this.label7);
            this.groupBox1.Controls.Add(this.label6);
            this.groupBox1.Controls.Add(this.relAltitudelabel);
            this.groupBox1.Controls.Add(this.serialTemperaturelabel);
            this.groupBox1.Controls.Add(this.serialPressurelabel);
            this.groupBox1.Controls.Add(this.label5);
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this.serialHeadinglabel);
            this.groupBox1.Controls.Add(this.label3);
            this.groupBox1.Controls.Add(this.serialVerticalLabel);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.serialAltitudeLabel);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Location = new System.Drawing.Point(172, 492);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(395, 195);
            this.groupBox1.TabIndex = 6;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Data";
            // 
            // avgTemperatureLabel
            // 
            this.avgTemperatureLabel.AutoSize = true;
            this.avgTemperatureLabel.Location = new System.Drawing.Point(340, 169);
            this.avgTemperatureLabel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.avgTemperatureLabel.Name = "avgTemperatureLabel";
            this.avgTemperatureLabel.Size = new System.Drawing.Size(14, 15);
            this.avgTemperatureLabel.TabIndex = 27;
            this.avgTemperatureLabel.Text = "0";
            // 
            // avgPressureLabel
            // 
            this.avgPressureLabel.AutoSize = true;
            this.avgPressureLabel.Location = new System.Drawing.Point(340, 138);
            this.avgPressureLabel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.avgPressureLabel.Name = "avgPressureLabel";
            this.avgPressureLabel.Size = new System.Drawing.Size(14, 15);
            this.avgPressureLabel.TabIndex = 26;
            this.avgPressureLabel.Text = "0";
            // 
            // avgVerticalSpeedLabel
            // 
            this.avgVerticalSpeedLabel.AutoSize = true;
            this.avgVerticalSpeedLabel.Location = new System.Drawing.Point(340, 82);
            this.avgVerticalSpeedLabel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.avgVerticalSpeedLabel.Name = "avgVerticalSpeedLabel";
            this.avgVerticalSpeedLabel.Size = new System.Drawing.Size(14, 15);
            this.avgVerticalSpeedLabel.TabIndex = 24;
            this.avgVerticalSpeedLabel.Text = "0";
            // 
            // avgAltitudeLabel
            // 
            this.avgAltitudeLabel.AutoSize = true;
            this.avgAltitudeLabel.Location = new System.Drawing.Point(340, 53);
            this.avgAltitudeLabel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.avgAltitudeLabel.Name = "avgAltitudeLabel";
            this.avgAltitudeLabel.Size = new System.Drawing.Size(14, 15);
            this.avgAltitudeLabel.TabIndex = 23;
            this.avgAltitudeLabel.Text = "0";
            // 
            // label17
            // 
            this.label17.AutoSize = true;
            this.label17.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label17.Location = new System.Drawing.Point(320, 22);
            this.label17.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label17.Name = "label17";
            this.label17.Size = new System.Drawing.Size(76, 17);
            this.label17.TabIndex = 22;
            this.label17.Text = "Averages";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(242, 22);
            this.label7.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(53, 17);
            this.label7.TabIndex = 21;
            this.label7.Text = "Actual";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(152, 22);
            this.label6.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(67, 17);
            this.label6.TabIndex = 20;
            this.label6.Text = "Relative";
            // 
            // relAltitudelabel
            // 
            this.relAltitudelabel.AutoSize = true;
            this.relAltitudelabel.Location = new System.Drawing.Point(169, 53);
            this.relAltitudelabel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.relAltitudelabel.Name = "relAltitudelabel";
            this.relAltitudelabel.Size = new System.Drawing.Size(14, 15);
            this.relAltitudelabel.TabIndex = 19;
            this.relAltitudelabel.Text = "0";
            // 
            // serialTemperaturelabel
            // 
            this.serialTemperaturelabel.AutoSize = true;
            this.serialTemperaturelabel.Location = new System.Drawing.Point(212, 169);
            this.serialTemperaturelabel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.serialTemperaturelabel.Name = "serialTemperaturelabel";
            this.serialTemperaturelabel.Size = new System.Drawing.Size(14, 15);
            this.serialTemperaturelabel.TabIndex = 18;
            this.serialTemperaturelabel.Text = "0";
            // 
            // serialPressurelabel
            // 
            this.serialPressurelabel.AutoSize = true;
            this.serialPressurelabel.Location = new System.Drawing.Point(212, 139);
            this.serialPressurelabel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.serialPressurelabel.Name = "serialPressurelabel";
            this.serialPressurelabel.Size = new System.Drawing.Size(14, 15);
            this.serialPressurelabel.TabIndex = 17;
            this.serialPressurelabel.Text = "0";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(6, 165);
            this.label5.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(166, 25);
            this.label5.TabIndex = 16;
            this.label5.Text = "Temperature (°C)";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(6, 135);
            this.label4.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(144, 25);
            this.label4.TabIndex = 15;
            this.label4.Text = "Pressure (hPa)";
            // 
            // serialHeadinglabel
            // 
            this.serialHeadinglabel.AutoSize = true;
            this.serialHeadinglabel.Location = new System.Drawing.Point(212, 112);
            this.serialHeadinglabel.Name = "serialHeadinglabel";
            this.serialHeadinglabel.Size = new System.Drawing.Size(14, 15);
            this.serialHeadinglabel.TabIndex = 14;
            this.serialHeadinglabel.Text = "0";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(6, 106);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(112, 25);
            this.label3.TabIndex = 13;
            this.label3.Text = "Heading (°)";
            // 
            // serialVerticalLabel
            // 
            this.serialVerticalLabel.AutoSize = true;
            this.serialVerticalLabel.Location = new System.Drawing.Point(212, 82);
            this.serialVerticalLabel.Name = "serialVerticalLabel";
            this.serialVerticalLabel.Size = new System.Drawing.Size(14, 15);
            this.serialVerticalLabel.TabIndex = 12;
            this.serialVerticalLabel.Text = "0";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(6, 77);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(191, 25);
            this.label2.TabIndex = 11;
            this.label2.Text = "Vertical Speed (m/s)";
            // 
            // serialAltitudeLabel
            // 
            this.serialAltitudeLabel.Location = new System.Drawing.Point(256, 53);
            this.serialAltitudeLabel.Name = "serialAltitudeLabel";
            this.serialAltitudeLabel.Size = new System.Drawing.Size(36, 18);
            this.serialAltitudeLabel.TabIndex = 10;
            this.serialAltitudeLabel.Text = "0";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(6, 47);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(112, 25);
            this.label1.TabIndex = 1;
            this.label1.Text = "Altitude (m)";
            // 
            // serialPort1
            // 
            this.serialPort1.PortName = "COM12";
            this.serialPort1.DataReceived += new System.IO.Ports.SerialDataReceivedEventHandler(this.serialPort1_DataReceived);
            // 
            // startButton
            // 
            this.startButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.startButton.Location = new System.Drawing.Point(573, 507);
            this.startButton.Name = "startButton";
            this.startButton.Size = new System.Drawing.Size(88, 32);
            this.startButton.TabIndex = 8;
            this.startButton.Text = "Start Serial";
            this.startButton.UseVisualStyleBackColor = true;
            this.startButton.Click += new System.EventHandler(this.startButton_Click);
            // 
            // stopButton
            // 
            this.stopButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.stopButton.Enabled = false;
            this.stopButton.Location = new System.Drawing.Point(573, 545);
            this.stopButton.Name = "stopButton";
            this.stopButton.Size = new System.Drawing.Size(88, 32);
            this.stopButton.TabIndex = 9;
            this.stopButton.Text = "Stop Serial";
            this.stopButton.UseVisualStyleBackColor = true;
            this.stopButton.Click += new System.EventHandler(this.stopButton_Click);
            // 
            // comboBox1
            // 
            this.comboBox1.AllowDrop = true;
            this.comboBox1.FormattingEnabled = true;
            this.comboBox1.Items.AddRange(new object[] {
            "COM1",
            "COM2",
            "COM3",
            "COM4",
            "COM5",
            "COM6",
            "COM7",
            "COM8"});
            this.comboBox1.Location = new System.Drawing.Point(573, 587);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new System.Drawing.Size(89, 21);
            this.comboBox1.TabIndex = 18;
            this.comboBox1.Text = "COM3";
            // 
            // resetRelButton
            // 
            this.resetRelButton.Location = new System.Drawing.Point(581, 613);
            this.resetRelButton.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.resetRelButton.Name = "resetRelButton";
            this.resetRelButton.Size = new System.Drawing.Size(73, 49);
            this.resetRelButton.TabIndex = 20;
            this.resetRelButton.Text = "Set relative \r\nto position";
            this.resetRelButton.UseVisualStyleBackColor = true;
            this.resetRelButton.Click += new System.EventHandler(this.resetRelButton_Click);
            // 
            // telemetryGroupBox
            // 
            this.telemetryGroupBox.Controls.Add(this.altiLabel);
            this.telemetryGroupBox.Controls.Add(this.tempLabel);
            this.telemetryGroupBox.Controls.Add(this.pressureLabel);
            this.telemetryGroupBox.Controls.Add(this.magLabelZ);
            this.telemetryGroupBox.Controls.Add(this.magLabelY);
            this.telemetryGroupBox.Controls.Add(this.magLabelX);
            this.telemetryGroupBox.Controls.Add(this.gyroLabelZ);
            this.telemetryGroupBox.Controls.Add(this.gyroLabelY);
            this.telemetryGroupBox.Controls.Add(this.gyroLabelX);
            this.telemetryGroupBox.Controls.Add(this.accelLabelZ);
            this.telemetryGroupBox.Controls.Add(this.accelLabelY);
            this.telemetryGroupBox.Controls.Add(this.accelLabelX);
            this.telemetryGroupBox.Controls.Add(this.label16);
            this.telemetryGroupBox.Controls.Add(this.label15);
            this.telemetryGroupBox.Controls.Add(this.label14);
            this.telemetryGroupBox.Controls.Add(this.label13);
            this.telemetryGroupBox.Controls.Add(this.label12);
            this.telemetryGroupBox.Controls.Add(this.label11);
            this.telemetryGroupBox.Controls.Add(this.label10);
            this.telemetryGroupBox.Controls.Add(this.label9);
            this.telemetryGroupBox.Controls.Add(this.label8);
            this.telemetryGroupBox.Location = new System.Drawing.Point(752, 384);
            this.telemetryGroupBox.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.telemetryGroupBox.Name = "telemetryGroupBox";
            this.telemetryGroupBox.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.telemetryGroupBox.Size = new System.Drawing.Size(250, 232);
            this.telemetryGroupBox.TabIndex = 21;
            this.telemetryGroupBox.TabStop = false;
            this.telemetryGroupBox.Text = "Telemetry";
            this.telemetryGroupBox.Visible = false;
            // 
            // altiLabel
            // 
            this.altiLabel.AutoSize = true;
            this.altiLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.altiLabel.Location = new System.Drawing.Point(170, 200);
            this.altiLabel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.altiLabel.Name = "altiLabel";
            this.altiLabel.Size = new System.Drawing.Size(16, 17);
            this.altiLabel.TabIndex = 20;
            this.altiLabel.Text = "0";
            this.altiLabel.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // tempLabel
            // 
            this.tempLabel.AutoSize = true;
            this.tempLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tempLabel.Location = new System.Drawing.Point(170, 170);
            this.tempLabel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.tempLabel.Name = "tempLabel";
            this.tempLabel.Size = new System.Drawing.Size(16, 17);
            this.tempLabel.TabIndex = 19;
            this.tempLabel.Text = "0";
            this.tempLabel.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // pressureLabel
            // 
            this.pressureLabel.AutoSize = true;
            this.pressureLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.pressureLabel.Location = new System.Drawing.Point(170, 140);
            this.pressureLabel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.pressureLabel.Name = "pressureLabel";
            this.pressureLabel.Size = new System.Drawing.Size(16, 17);
            this.pressureLabel.TabIndex = 18;
            this.pressureLabel.Text = "0";
            this.pressureLabel.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // magLabelZ
            // 
            this.magLabelZ.AutoSize = true;
            this.magLabelZ.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.magLabelZ.Location = new System.Drawing.Point(212, 109);
            this.magLabelZ.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.magLabelZ.Name = "magLabelZ";
            this.magLabelZ.Size = new System.Drawing.Size(16, 17);
            this.magLabelZ.TabIndex = 17;
            this.magLabelZ.Text = "0";
            this.magLabelZ.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // magLabelY
            // 
            this.magLabelY.AutoSize = true;
            this.magLabelY.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.magLabelY.Location = new System.Drawing.Point(170, 109);
            this.magLabelY.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.magLabelY.Name = "magLabelY";
            this.magLabelY.Size = new System.Drawing.Size(16, 17);
            this.magLabelY.TabIndex = 16;
            this.magLabelY.Text = "0";
            this.magLabelY.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // magLabelX
            // 
            this.magLabelX.AutoSize = true;
            this.magLabelX.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.magLabelX.Location = new System.Drawing.Point(124, 109);
            this.magLabelX.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.magLabelX.Name = "magLabelX";
            this.magLabelX.Size = new System.Drawing.Size(16, 17);
            this.magLabelX.TabIndex = 15;
            this.magLabelX.Text = "0";
            this.magLabelX.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // gyroLabelZ
            // 
            this.gyroLabelZ.AutoSize = true;
            this.gyroLabelZ.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gyroLabelZ.Location = new System.Drawing.Point(212, 76);
            this.gyroLabelZ.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.gyroLabelZ.Name = "gyroLabelZ";
            this.gyroLabelZ.Size = new System.Drawing.Size(16, 17);
            this.gyroLabelZ.TabIndex = 14;
            this.gyroLabelZ.Text = "0";
            this.gyroLabelZ.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // gyroLabelY
            // 
            this.gyroLabelY.AutoSize = true;
            this.gyroLabelY.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gyroLabelY.Location = new System.Drawing.Point(170, 76);
            this.gyroLabelY.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.gyroLabelY.Name = "gyroLabelY";
            this.gyroLabelY.Size = new System.Drawing.Size(16, 17);
            this.gyroLabelY.TabIndex = 13;
            this.gyroLabelY.Text = "0";
            this.gyroLabelY.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // gyroLabelX
            // 
            this.gyroLabelX.AutoSize = true;
            this.gyroLabelX.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gyroLabelX.Location = new System.Drawing.Point(124, 75);
            this.gyroLabelX.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.gyroLabelX.Name = "gyroLabelX";
            this.gyroLabelX.Size = new System.Drawing.Size(16, 17);
            this.gyroLabelX.TabIndex = 12;
            this.gyroLabelX.Text = "0";
            this.gyroLabelX.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // accelLabelZ
            // 
            this.accelLabelZ.AutoSize = true;
            this.accelLabelZ.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.accelLabelZ.Location = new System.Drawing.Point(212, 40);
            this.accelLabelZ.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.accelLabelZ.Name = "accelLabelZ";
            this.accelLabelZ.Size = new System.Drawing.Size(16, 17);
            this.accelLabelZ.TabIndex = 11;
            this.accelLabelZ.Text = "0";
            this.accelLabelZ.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // accelLabelY
            // 
            this.accelLabelY.AutoSize = true;
            this.accelLabelY.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.accelLabelY.Location = new System.Drawing.Point(170, 40);
            this.accelLabelY.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.accelLabelY.Name = "accelLabelY";
            this.accelLabelY.Size = new System.Drawing.Size(16, 17);
            this.accelLabelY.TabIndex = 10;
            this.accelLabelY.Text = "0";
            this.accelLabelY.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // accelLabelX
            // 
            this.accelLabelX.AutoSize = true;
            this.accelLabelX.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.accelLabelX.Location = new System.Drawing.Point(124, 40);
            this.accelLabelX.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.accelLabelX.Name = "accelLabelX";
            this.accelLabelX.Size = new System.Drawing.Size(16, 17);
            this.accelLabelX.TabIndex = 9;
            this.accelLabelX.Text = "0";
            this.accelLabelX.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // label16
            // 
            this.label16.AutoSize = true;
            this.label16.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label16.Location = new System.Drawing.Point(210, 7);
            this.label16.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label16.Name = "label16";
            this.label16.Size = new System.Drawing.Size(24, 25);
            this.label16.TabIndex = 8;
            this.label16.Text = "Z";
            // 
            // label15
            // 
            this.label15.AutoSize = true;
            this.label15.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label15.Location = new System.Drawing.Point(168, 7);
            this.label15.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(25, 25);
            this.label15.TabIndex = 7;
            this.label15.Text = "Y";
            // 
            // label14
            // 
            this.label14.AutoSize = true;
            this.label14.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label14.Location = new System.Drawing.Point(122, 7);
            this.label14.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(26, 25);
            this.label14.TabIndex = 6;
            this.label14.Text = "X";
            // 
            // label13
            // 
            this.label13.AutoSize = true;
            this.label13.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label13.Location = new System.Drawing.Point(22, 198);
            this.label13.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(80, 17);
            this.label13.TabIndex = 5;
            this.label13.Text = "Altitude (m)";
            // 
            // label12
            // 
            this.label12.AutoSize = true;
            this.label12.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label12.Location = new System.Drawing.Point(22, 169);
            this.label12.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(119, 17);
            this.label12.TabIndex = 4;
            this.label12.Text = "Temperature (°C)";
            // 
            // label11
            // 
            this.label11.AutoSize = true;
            this.label11.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label11.Location = new System.Drawing.Point(22, 140);
            this.label11.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(104, 17);
            this.label11.TabIndex = 3;
            this.label11.Text = "Pressure (hPa)";
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label10.Location = new System.Drawing.Point(22, 70);
            this.label10.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(85, 17);
            this.label10.TabIndex = 2;
            this.label10.Text = "Gyro (rad/s)";
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.Location = new System.Drawing.Point(22, 104);
            this.label9.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(66, 17);
            this.label9.TabIndex = 1;
            this.label9.Text = "Mag (uT)";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.Location = new System.Drawing.Point(22, 37);
            this.label8.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(93, 17);
            this.label8.TabIndex = 0;
            this.label8.Text = "Accel (m/s^2)";
            // 
            // telemetryCheckBox1
            // 
            this.telemetryCheckBox1.AutoSize = true;
            this.telemetryCheckBox1.Location = new System.Drawing.Point(581, 666);
            this.telemetryCheckBox1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.telemetryCheckBox1.Name = "telemetryCheckBox1";
            this.telemetryCheckBox1.Size = new System.Drawing.Size(83, 19);
            this.telemetryCheckBox1.TabIndex = 22;
            this.telemetryCheckBox1.Text = "Telemetry";
            this.telemetryCheckBox1.UseVisualStyleBackColor = true;
            this.telemetryCheckBox1.CheckedChanged += new System.EventHandler(this.telemetryCheckBox1_CheckedChanged);
            // 
            // clearMarkersButton
            // 
            this.clearMarkersButton.Location = new System.Drawing.Point(691, 621);
            this.clearMarkersButton.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.clearMarkersButton.Name = "clearMarkersButton";
            this.clearMarkersButton.Size = new System.Drawing.Size(80, 38);
            this.clearMarkersButton.TabIndex = 23;
            this.clearMarkersButton.Text = "Clear Markers";
            this.clearMarkersButton.UseVisualStyleBackColor = true;
            this.clearMarkersButton.Click += new System.EventHandler(this.clearMarkersButton_Click);
            // 
            // gMapControl1
            // 
            this.gMapControl1.Bearing = 0F;
            this.gMapControl1.CanDragMap = true;
            this.gMapControl1.EmptyTileColor = System.Drawing.Color.Navy;
            this.gMapControl1.GrayScaleMode = false;
            this.gMapControl1.HelperLineOption = GMap.NET.WindowsForms.HelperLineOptions.DontShow;
            this.gMapControl1.LevelsKeepInMemmory = 5;
            this.gMapControl1.Location = new System.Drawing.Point(188, 11);
            this.gMapControl1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.gMapControl1.MarkersEnabled = true;
            this.gMapControl1.MaxZoom = 2;
            this.gMapControl1.MinZoom = 2;
            this.gMapControl1.MouseWheelZoomType = GMap.NET.MouseWheelZoomType.MousePositionAndCenter;
            this.gMapControl1.Name = "gMapControl1";
            this.gMapControl1.NegativeMode = false;
            this.gMapControl1.PolygonsEnabled = true;
            this.gMapControl1.RetryLoadTile = 0;
            this.gMapControl1.RoutesEnabled = true;
            this.gMapControl1.ScaleMode = GMap.NET.WindowsForms.ScaleModes.Integer;
            this.gMapControl1.SelectedAreaFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(65)))), ((int)(((byte)(105)))), ((int)(((byte)(225)))));
            this.gMapControl1.ShowTileGridLines = false;
            this.gMapControl1.Size = new System.Drawing.Size(807, 338);
            this.gMapControl1.TabIndex = 24;
            this.gMapControl1.Zoom = 0D;
            // 
            // addMarkerButton
            // 
            this.addMarkerButton.Location = new System.Drawing.Point(794, 621);
            this.addMarkerButton.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.addMarkerButton.Name = "addMarkerButton";
            this.addMarkerButton.Size = new System.Drawing.Size(81, 38);
            this.addMarkerButton.TabIndex = 25;
            this.addMarkerButton.Text = "Add Marker";
            this.addMarkerButton.UseVisualStyleBackColor = true;
            this.addMarkerButton.Click += new System.EventHandler(this.addMarkerButton_Click);
            // 
            // zoomLabel
            // 
            this.zoomLabel.AutoSize = true;
            this.zoomLabel.Location = new System.Drawing.Point(596, 358);
            this.zoomLabel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.zoomLabel.Name = "zoomLabel";
            this.zoomLabel.Size = new System.Drawing.Size(91, 15);
            this.zoomLabel.TabIndex = 26;
            this.zoomLabel.Text = "Zoom Level: 12";
            // 
            // timeLabel
            // 
            this.timeLabel.AutoSize = true;
            this.timeLabel.Location = new System.Drawing.Point(724, 358);
            this.timeLabel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.timeLabel.Name = "timeLabel";
            this.timeLabel.Size = new System.Drawing.Size(76, 15);
            this.timeLabel.TabIndex = 27;
            this.timeLabel.Text = "Time (UTC): ";
            // 
            // showGraphButton
            // 
            this.showGraphButton.Location = new System.Drawing.Point(898, 621);
            this.showGraphButton.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.showGraphButton.Name = "showGraphButton";
            this.showGraphButton.Size = new System.Drawing.Size(89, 38);
            this.showGraphButton.TabIndex = 28;
            this.showGraphButton.Text = "Show Graph";
            this.showGraphButton.UseVisualStyleBackColor = true;
            this.showGraphButton.Click += new System.EventHandler(this.showGraphButton_Click);
            // 
            // statusLabel
            // 
            this.statusLabel.AutoSize = true;
            this.statusLabel.Location = new System.Drawing.Point(898, 358);
            this.statusLabel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.statusLabel.Name = "statusLabel";
            this.statusLabel.Size = new System.Drawing.Size(41, 15);
            this.statusLabel.TabIndex = 29;
            this.statusLabel.Text = "Status";
            // 
            // fileLabel
            // 
            this.fileLabel.AutoSize = true;
            this.fileLabel.Location = new System.Drawing.Point(798, 670);
            this.fileLabel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.fileLabel.Name = "fileLabel";
            this.fileLabel.Size = new System.Drawing.Size(54, 15);
            this.fileLabel.TabIndex = 30;
            this.fileLabel.Text = "fileLabel";
            // 
            // randomGenButton
            // 
            this.randomGenButton.Enabled = false;
            this.randomGenButton.Location = new System.Drawing.Point(863, 663);
            this.randomGenButton.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.randomGenButton.Name = "randomGenButton";
            this.randomGenButton.Size = new System.Drawing.Size(62, 25);
            this.randomGenButton.TabIndex = 31;
            this.randomGenButton.Text = "Add random";
            this.randomGenButton.UseVisualStyleBackColor = true;
            this.randomGenButton.Click += new System.EventHandler(this.randomGenButton_Click);
            // 
            // gpsStatusLabel
            // 
            this.gpsStatusLabel.AutoSize = true;
            this.gpsStatusLabel.Location = new System.Drawing.Point(676, 670);
            this.gpsStatusLabel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.gpsStatusLabel.Name = "gpsStatusLabel";
            this.gpsStatusLabel.Size = new System.Drawing.Size(69, 15);
            this.gpsStatusLabel.TabIndex = 32;
            this.gpsStatusLabel.Text = "GPS Status";
            // 
            // leftCameraButton
            // 
            this.leftCameraButton.Location = new System.Drawing.Point(562, 433);
            this.leftCameraButton.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.leftCameraButton.Name = "leftCameraButton";
            this.leftCameraButton.Size = new System.Drawing.Size(52, 35);
            this.leftCameraButton.TabIndex = 33;
            this.leftCameraButton.Text = "Left";
            this.leftCameraButton.UseVisualStyleBackColor = true;
            this.leftCameraButton.Click += new System.EventHandler(this.leftCameraButton_Click);
            // 
            // centerCameraButton
            // 
            this.centerCameraButton.Location = new System.Drawing.Point(625, 433);
            this.centerCameraButton.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.centerCameraButton.Name = "centerCameraButton";
            this.centerCameraButton.Size = new System.Drawing.Size(52, 35);
            this.centerCameraButton.TabIndex = 34;
            this.centerCameraButton.Text = "Center";
            this.centerCameraButton.UseVisualStyleBackColor = true;
            this.centerCameraButton.Click += new System.EventHandler(this.centerCameraButton_Click);
            // 
            // rightCameraButton
            // 
            this.rightCameraButton.Location = new System.Drawing.Point(685, 433);
            this.rightCameraButton.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.rightCameraButton.Name = "rightCameraButton";
            this.rightCameraButton.Size = new System.Drawing.Size(52, 35);
            this.rightCameraButton.TabIndex = 35;
            this.rightCameraButton.Text = "Right";
            this.rightCameraButton.UseVisualStyleBackColor = true;
            this.rightCameraButton.Click += new System.EventHandler(this.rightCameraButton_Click);
            // 
            // cameraLabel
            // 
            this.cameraLabel.Location = new System.Drawing.Point(562, 392);
            this.cameraLabel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.cameraLabel.Name = "cameraLabel";
            this.cameraLabel.Size = new System.Drawing.Size(176, 39);
            this.cameraLabel.TabIndex = 36;
            this.cameraLabel.Text = "Camera Control";
            this.cameraLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // tempIndicator1
            // 
            this.tempIndicator1.Location = new System.Drawing.Point(182, 366);
            this.tempIndicator1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.tempIndicator1.Name = "tempIndicator1";
            this.tempIndicator1.Size = new System.Drawing.Size(376, 126);
            this.tempIndicator1.TabIndex = 19;
            this.tempIndicator1.Text = "tempIndicator1";
            // 
            // horizonInstrumentControl1
            // 
            this.horizonInstrumentControl1.Location = new System.Drawing.Point(10, 11);
            this.horizonInstrumentControl1.Name = "horizonInstrumentControl1";
            this.horizonInstrumentControl1.Size = new System.Drawing.Size(156, 156);
            this.horizonInstrumentControl1.TabIndex = 3;
            this.horizonInstrumentControl1.Text = "horizonInstrumentControl1";
            // 
            // verticalSpeedInstrumentControl1
            // 
            this.verticalSpeedInstrumentControl1.Location = new System.Drawing.Point(10, 340);
            this.verticalSpeedInstrumentControl1.Name = "verticalSpeedInstrumentControl1";
            this.verticalSpeedInstrumentControl1.Size = new System.Drawing.Size(156, 163);
            this.verticalSpeedInstrumentControl1.TabIndex = 5;
            this.verticalSpeedInstrumentControl1.Text = "verticalSpeedInstrumentControl1";
            // 
            // headingIndicatorInstrumentControl1
            // 
            this.headingIndicatorInstrumentControl1.Location = new System.Drawing.Point(10, 510);
            this.headingIndicatorInstrumentControl1.Name = "headingIndicatorInstrumentControl1";
            this.headingIndicatorInstrumentControl1.Size = new System.Drawing.Size(156, 172);
            this.headingIndicatorInstrumentControl1.TabIndex = 4;
            this.headingIndicatorInstrumentControl1.Text = "headingIndicatorInstrumentControl1";
            // 
            // altimeterInstrumentControl1
            // 
            this.altimeterInstrumentControl1.Location = new System.Drawing.Point(10, 173);
            this.altimeterInstrumentControl1.Name = "altimeterInstrumentControl1";
            this.altimeterInstrumentControl1.Size = new System.Drawing.Size(154, 161);
            this.altimeterInstrumentControl1.TabIndex = 2;
            this.altimeterInstrumentControl1.Text = "altimeterInstrumentControl1";
            // 
            // DemoWindow
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSize = true;
            this.ClientSize = new System.Drawing.Size(1011, 693);
            this.Controls.Add(this.cameraLabel);
            this.Controls.Add(this.rightCameraButton);
            this.Controls.Add(this.centerCameraButton);
            this.Controls.Add(this.leftCameraButton);
            this.Controls.Add(this.gpsStatusLabel);
            this.Controls.Add(this.randomGenButton);
            this.Controls.Add(this.fileLabel);
            this.Controls.Add(this.statusLabel);
            this.Controls.Add(this.showGraphButton);
            this.Controls.Add(this.timeLabel);
            this.Controls.Add(this.zoomLabel);
            this.Controls.Add(this.addMarkerButton);
            this.Controls.Add(this.startButton);
            this.Controls.Add(this.gMapControl1);
            this.Controls.Add(this.clearMarkersButton);
            this.Controls.Add(this.telemetryCheckBox1);
            this.Controls.Add(this.resetRelButton);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.tempIndicator1);
            this.Controls.Add(this.comboBox1);
            this.Controls.Add(this.horizonInstrumentControl1);
            this.Controls.Add(this.stopButton);
            this.Controls.Add(this.verticalSpeedInstrumentControl1);
            this.Controls.Add(this.headingIndicatorInstrumentControl1);
            this.Controls.Add(this.altimeterInstrumentControl1);
            this.Controls.Add(this.telemetryGroupBox);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "DemoWindow";
            this.Text = "CanSat Display";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.DemoWinow_FormClosing);
            this.Load += new System.EventHandler(this.DemoWinow_Load);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.telemetryGroupBox.ResumeLayout(false);
            this.telemetryGroupBox.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private AltimeterInstrumentControl altimeterInstrumentControl1;
        private AttitudeIndicatorInstrumentControl horizonInstrumentControl1;
        private HeadingIndicatorInstrumentControl headingIndicatorInstrumentControl1;
        private VerticalSpeedIndicatorInstrumentControl verticalSpeedInstrumentControl1;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Label label1;
        private System.IO.Ports.SerialPort serialPort1;
        private System.Windows.Forms.Button startButton;
        private System.Windows.Forms.Button stopButton;
        private System.Windows.Forms.Label serialAltitudeLabel;
        private System.Windows.Forms.Label serialVerticalLabel;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label serialHeadinglabel;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.ComboBox comboBox1;
        private TempIndicator tempIndicator1;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label relAltitudelabel;
        private System.Windows.Forms.Label serialTemperaturelabel;
        private System.Windows.Forms.Label serialPressurelabel;
        private System.Windows.Forms.Button resetRelButton;
        private System.Windows.Forms.GroupBox telemetryGroupBox;
        private System.Windows.Forms.Label altiLabel;
        private System.Windows.Forms.Label tempLabel;
        private System.Windows.Forms.Label pressureLabel;
        private System.Windows.Forms.Label magLabelZ;
        private System.Windows.Forms.Label magLabelY;
        private System.Windows.Forms.Label magLabelX;
        private System.Windows.Forms.Label gyroLabelZ;
        private System.Windows.Forms.Label gyroLabelY;
        private System.Windows.Forms.Label gyroLabelX;
        private System.Windows.Forms.Label accelLabelZ;
        private System.Windows.Forms.Label accelLabelY;
        private System.Windows.Forms.Label accelLabelX;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.CheckBox telemetryCheckBox1;
        private System.Windows.Forms.Label avgTemperatureLabel;
        private System.Windows.Forms.Label avgPressureLabel;
        private System.Windows.Forms.Label avgVerticalSpeedLabel;
        private System.Windows.Forms.Label avgAltitudeLabel;
        private System.Windows.Forms.Label label17;
        private System.Windows.Forms.Button clearMarkersButton;
        private GMap.NET.WindowsForms.GMapControl gMapControl1;
        private System.Windows.Forms.Button addMarkerButton;
        private System.Windows.Forms.Label zoomLabel;
        private System.Windows.Forms.Label timeLabel;
        private System.Windows.Forms.Button showGraphButton;
        private System.Windows.Forms.Label statusLabel;
        private System.Windows.Forms.Label fileLabel;
        private System.Windows.Forms.Button randomGenButton;
        private System.Windows.Forms.Label gpsStatusLabel;
        private System.Windows.Forms.Button leftCameraButton;
        private System.Windows.Forms.Button centerCameraButton;
        private System.Windows.Forms.Button rightCameraButton;
        private System.Windows.Forms.Label cameraLabel;
    }
}

